### ISSUE TITLE
Timebox: API play / pause / state

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-documentation#10]
**As developers** we need to agree on a common playback API where applicable so that our products are meaningfully aligned.

# Acceptance criteria

- Decisions have been taken regarding play / pause APIs.
- Identified states have been named consistently.

# Tasks

- [x] Discuss play / pause API.
- [x] Discuss playback states.
- [x] Create issues where alignment is required.
