### ISSUE TITLE
Migrate from Notion to Confluence

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-documentation#103]
**As an SRG SSR employee** I want to access most relevant articles, currently in Notion, in Confluence instead.

## Acceptance criteria

- Relevant Pillarbox documentation is accessible on Confluence instead of Notion.

## Tasks

- [x] Create Pillarbox space on Confluence.
- [x] List relevant Notion pages to migrate.
- [x] Migrate relevant Notion pages.
- [x] Close the Notion account.
