### ISSUE TITLE
Add a way to hook into Pillarbox page view events

### ISSUE THREAD

**Issue by waliid** [SRGSSR/pillarbox-documentation#114]
**As an RTS Apple developer**  I would like to be able to integrated Chartbeat, Google Analytics and so on for page view events.

# Acceptance criteria

- Feedback has been provided to the RTS team.
- Stories have been created if any job have to be done on our side.

# Tasks

- [x] Contact @oiledCode to have more information.
- [x] Discuss with the team.
- [x] Create corresponding issues if needed.
- [x] Notify @oiledCode.

**Comment by defagos** [comment]
We could:

- Offer an API to hook into Pillarbox events, letting apps integrate other frameworks reusing the same events.
- Alternatively (maybe simpler) we could post a notification so that implementations can listen to these notifications instead.
