### ISSUE TITLE
Make product goals more visible on GitHub

### ISSUE THREAD

**Issue by StaehliJ** [SRGSSR/pillarbox-documentation#19]
**As a stakeholder** I want to have a better understanding of the main product goals. **As a PO** I need to have a better overview of the goals and associated tasks. **As a team member** I need a tool that helps me in my work.

# Acceptance criteria

- Product goals are visible on the GitHub board.
- Product goals can be consolidated among platforms.
- The board is easy to understand and use.

# Tasks

- [x] Discuss desired behavior with the team.
- [x] Use milestones to deal with product goals and attach related issues.
- [x] Issues might not be attached to a milestone for other unrelated work.
- [x] The Epic field is removed.
- [x] The Epics tab is removed.
- [x] Update [board setup documentation](https://github.com/SRGSSR/srgletterbox-web/issues/712) accordingly. Maybe move this documentation to the documentation repository.
- [x] Discuss draft workflow.

**Comment by defagos** [comment]
Here are the changes we made:

- We removed a few unused tabs.
- The _Product Backlog_ tab now only shows issues with the _Draft_ or _Backlog_ status. Issues are grouped according to this status.
- Milestones serve as replacement for epics, which have been removed. We introduced a _Current Milestone_ tab to display the current milestone (i.e. the main current focus).
- We renamed _Test_ as _Testing_ to avoid confusion with a board which would have been created for a quick test.

We also agreed to discuss next how we could better integrate testing or code review in our boards.
