### ISSUE TITLE
Align tracking API between platforms where appropriate

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-documentation#23]
**As a developer implementing Pillarbox** I would like to have a consistent API naming scheme where possible so that we can better discuss implementation across platforms

# Acceptance criteria

- The team discussed API naming after the custom tracking API has been implemented.
- Issues have been created for alignment proposals.

# Tasks

- [x] Discuss misalignments or questions, e.g.:
   - [x] Track page view / track event?
   - [x] Use `name` as main track parameter for page views / events? Or use `title` for pages and `name` for events? Or something else?
- [x] Create issues if needed.

**Comment by defagos** [comment]
As discussed with @waliid and @StaehliJ:

# Generic labels

We drop the ability to send arbitrary label dictionaries. We namely do not control Mediapulse specifications and, similarly for SRG SSR analytics, new labels require agreement and new mappings. So there is really no need for our API to provide this kind of flexibility anymore, especially now that teams can implement their own trackers.

# Events

The name _hidden event_ is dropped and becomes simply _event_. Sending an event is made with a dedicated `sendEvent` API endpoint with `name`, `type`, `value`, `source` and `extra[1-5]` parameters.

We do not introduce an object for event data like before. Using default values the API is quite ergonomic as it is.

# Page views

To avoid confusion with events we will simply call page view events _page views_. The corresponding API endpoint is `sendPageView` with `title` and `levels` parameters.

We do not introduce an object for event data like before. Using default values the API is quite ergonomic as it is.

# Naming conventions

On Apple platforms the APIs were historically named `trackPageView` and `trackHiddenEvent`, but we decided to reserve `track` for more elaborate behaviors (e.g. remove duplicate events on Android). `send` methods are meant to simply send events without additional complex logic.

We also decided to keep the page view `title` and event `name` parameter names clearly different so that users of our libraries can clearly differentiate between both.
