### ISSUE TITLE
📌 comScore analytics open questions

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-documentation#25]
**As a Pillarbox developer** I need to have some comScore-related questions answered so that I can provide a compliant implementation.

# Acceptance criteria

- The questions listed below have been answered.
- Corresponding issues have been created for any necessary implementation work.

# Tasks

- [x] Get an answer for the questions below.
- [x] Create issues if needed on Apple Pillarbox repository.
- [x] Create issues if needed on Android Pillarbox repository.
- [x] Get Mediapulse page view specification documentation from the GD.

# General questions

1. ✅ 🍎 What are the exact consequences if AdSupport.framework is not linked? How is privacy affected if we link against it?
2. ✅ 🍎 Can you confirm that no events are sent if the device is offline? Is there a way to disable this behavior for test purposes?

# Page view questions

1. ✅ Do we still need [special character formatting](https://github.com/SRGSSR/srganalytics-apple/blob/develop/Sources/SRGAnalytics/NSString%2BSRGAnalytics.m)? The web portal does not apply these formatting rules anymore. Most precisely, if the answer is (at least partially) yes:
    - Should we use lowercase only?
    - Is special character replacement required?
    - Are requirements described in comScore integration guide, section 2.4, sufficient, and actually what we need to implement? (i.e. use `ns_category` and provide just a name, not a full path built client-side)
2. ✅ Do we need to be able to send arbitrary labels in page view events? Or should we restrict to only those mentioned in specifications we have?
3. ✅ Can / should we [count again](https://github.com/SRGSSR/srganalytics-apple/issues/52) a view when it is again revealed by returning from a view pushed after it?
4. ✅ How should screens arranged in a split view be measured? Are two page views acceptable or should we ensure only the parent screen is measured?
5. ✅ What about page views in background for a CarPlay / Android Auto experience?
6. ✅ Is it ok if we simply provide the page title in `c8`?

# Streaming questions

1. ✅ Is it correct that this buffer / seek start / stop events are important to ensure that the comScore state machine has correct behaviors (e.g. no heartbeats when the player is stuck buffering)? Official documentation never mentions it.
2. ✅ When should a _user experience_ be reported? What does _user experience_ exactly mean? What are the recommendations? (e.g. should a UX be reported if playback has been paused but can be resumed?). Are calls to `notifyUxActive` and `notifyUxInactive` reference counted?
3. ✅ Should we still use a threshold for the DVR timeshift value we send, below which the value is rounded to 0? If yes to what purpose? Does it make internal calculations better or worse somehow?
4. ✅ How is the DVR live edge offset `ns_st_ldo` taken into account in measurements? Is there a problem if DVR playback starts at the live edge with a non-zero value?
5. ✅ 🍎 Can you confirm that no events are sent if a play is followed by an end less than ~5 afterwards? Is there a way to reduce this value for test purposes?
6. ✅ What should we do for video in [background](https://github.com/SRGSSR/pillarbox-apple/commit/02a7be8)? Can we still measure it? It is namely difficult to detect whether the video is playing in the foreground with an attached view or not, so could we just track video in general without any problems?

# Resources

Some resources might be outdated:

- https://confluence.srg.beecollaboration.com/pages/viewpage.action?pageId=13188565
- https://confluence.srg.beecollaboration.com/pages/viewpage.action?pageId=44186760
- https://jira.srg.beecollaboration.com/browse/PLAYRTS-1733
- https://confluence.srg.beecollaboration.com/pages/viewpage.action?pageId=13189316
- https://confluence.srg.beecollaboration.com/pages/viewpage.action?spaceKey=INTFORSCHUNG&title=Digital+Analytics+SRG+Home
- https://confluence.srg.beecollaboration.com/display/SRGPLAY/Analytics+archives
- https://confluence.srg.beecollaboration.com/display/INTFORSCHUNG/Technical+Implementation+Media+Players

**Comment by defagos** [comment]
# General questions

1.
2.

 # Page view questions

1.
2.
3.
4.
5.
6.

# Streaming questions

1.
2.
3.
4.
5.

**Comment by defagos** [comment]
We received access to a [documentation SharePoint](https://ktglbuc.sharepoint.com/sites/TechGroupMediapulseOnlineData) with several documents about Mediapulse integration.

**Comment by defagos** [comment]
All questions answered and dedicated tasks created. Done.
