### ISSUE TITLE
Validate analytics with Mediapulse / comScore

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-documentation#28]
**As a Mediapulse analyst** I want to be sure that Mediapulse analytics standards are implemented according to the specifications by all SRG SSR apps depending on Pillarbox.

# Acceptance criteria

- The Pillarbox demo has been validated by Mediapulse testers.

# Tasks

- [x] Ensure that page views and streaming analytics can be tested in the Pillarbox demo.
- [x] Submit the demo to Mediapulse testers (invite and add build to test).
- [x] Validate Apple implementation.
- [x] Validate Android implementation.
- [x] Validate web implementation.

**Comment by defagos** [comment]
Versions sent for validation. Keeping this task in code review for feedbacks.

**Comment by defagos** [comment]
Validation received for Apple and Android implementations. Done.

**Comment by defagos** [comment]
We weren't aware we had to separately validate streaming analytics with comScore as well. The request has been sent and this issue reopened until we get a feedback.

**Comment by defagos** [comment]
Some issues have been found. [Here is the corresponding work](https://github.com/SRGSSR/pillarbox-apple/issues/603) to be done for Apple platforms.

**Comment by defagos** [comment]
All good for Android and Apple platforms.

**Comment by amtins** [comment]
To date, it would appear that all `Pillarbox` have `passed Comscore validation`, please refer to the e-mail of 28.11.2023 -  _Mediapulse - Streaming (OTV) - Pillarbox Demo Player is Validated_

However, two questions remain unanswered:

> Just to be sure I did not miss anything, could you please confirm that there are no other functionality I did not test ?

> And could you please confirm that the Pillarbox player is going to be implemented in production only with the listed functionalities that were validated ?

Finally, the e-mail reminds us that if **any changes are made to the various validated points, Comscore must be informed so that a revalidation can be carried out**.

**Comment by amtins** [comment]
Both open questions were answered for Pillarbox Web.

**Comment by defagos** [comment]
Same for the mobile. Can we now close this issue?
