### ISSUE TITLE
Cross-check analytics on all platforms

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-documentation#29]
**As a Pillarbox team member** I want to have a better understanding of differences between Android and iOS analytics implementations. This will allow us to:

- Ask our analytics teams if differences we find are acceptable.
- Create dedicated tasks to align the implementations where needed.

# Acceptance criteria

- Android and iOS implementations have been compared.
- Differences have been reported.
- Any new questions have been added to #25 and #26.

# Tasks

- [ ] Have the Android team investigate the iOS implementation and report inconsistencies.
- [x] Have the iOS team investigate the Android implementation and report inconsistencies.
- [ ] Collect inconsistencies and write issues if possible.
- [ ] Add questions about other inconsistencies to #25 and #26.

**Comment by defagos** [comment]
The iOS team compared both implementations (and Letterbox as well sometimes) and found some issues and differences.

# iOS bugs

We found a few issues, see #410, #411 and #412.

**Comment by StaehliJ** [comment]
Json request has not the same hierarchy
- iOS all properties a flatten at the root
- Android all properties are in a properties field

**Comment by StaehliJ** [comment]
### Android potential bugs (needs clarification)

- When navigating between playlist items a seek event is sent for Commanders Act, and a pause event is sent for comScore. Can this noise be avoided? This potential issue has been fixed. (0.0.4)
- When starting DVR playback the ns_st_ldo value can be quite large. Why is this value not zero? No compute are done on the position for live stream, it is the live edge position send by the player.
- When seeking while the player is paused the player is emitting a seek event. Can this be avoided? Have to be decided to continue or not this behaviors.
