### ISSUE TITLE
Adjust support policies

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-documentation#30]
**As a developer integrating Pillarbox and Letterbox** I want to clearly understand the respective support policies so that I can better plan migration from Letterbox to Pillarbox.

# Acceptance criteria

- The support policies are documented for all platforms.

# Tasks

- [x] The support policy for Apple platforms is documented.
- [x] The support policy for the Android platform is documented.
- [x] The support policy for the web is documented.

**Comment by defagos** [comment]
The [Apple policy](https://pillarbox.notion.site/Apple-platforms-18b6255b70b340c4bd349e40c2c2230a?pvs=4) has been updated to account for [recent decisions](https://www.notion.so/pillarbox/R-trospectives-a618df0cfd7444fa91bfe15b86283bb3?pvs=4).

**Comment by defagos** [comment]
The [web policy](https://srgssr-pillarbox-play.notion.site/Web-platforms-1127856f4b2f4430b50019ec55a538b1) has been updated as well.
