### ISSUE TITLE
Fix RTS / RSI stream packaging when AES encryption is involved

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-documentation#42]
**As a user**  I want to have the same good user experience with RSI TV series or RTS documentaries as with other kinds of contents (news, e.g.).

Currently seeking does not work as smoothly with these contents. Moreover the Apple TV standard playback UI shows an empty thumbnail while seeking, which is useless.

# Context

RTS / RSI stream packaging delivers `EXT-X-I-FRAME-STREAM-INF` playlists but those are broken because of the AES encryption. When fast forwarding the player cannot read these frames and therefore remains stuck. This explains why the Apple TV does not present thumbnails and why the player in general remains stuck at the seek start time instead of smoothly coping with seek requests.

We should get rid of these I-frame playlists. They are not useful anyway and just make the user experience worse.

# Acceptance criteria

- The player is able to smoothly cope with seek requests when playing RSI TV series or RTS documentaries, for example.

# Tasks

- [x] Discuss the matter with @bgaudaen.
- [x] Update stream packaging to remove I-frame playlists.
- [x] Notify RSI so that their packaging is updated as well.
- [x] Check in players.

**Comment by defagos** [comment]
As discussed with @bgaudaen:

- Short-term fix: Remove I-frame playlist with `vod_hls_output_iframes_playlist` parameter set to off in the corresponding [configuration](https://github.com/SRGSSR/rts-media-delivery/blob/main/helm/video-delivery/templates/_nginx.conf.tpl).
- Mid-term solution: Use same fmp4 configuration for CH content as well.

Must notify RSI so that they can do the fix as well.

**Comment by defagos** [comment]
We must notify Ivan at RSI so that he can forward the information further. We can provide the [corresponding change](https://github.com/SRGSSR/rts-media-delivery/blob/main/helm/video-delivery/templates/_nginx.conf.tpl#L205C1-L205C1) as information.

**Comment by defagos** [comment]
RSI has been contacted. Done.
