### ISSUE TITLE
User consent support in Letterbox / Pillarbox

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-documentation#46]
**As a team member** I need to better understand app needs regarding the new user consent support. **As an app developer** integrating SRG mobile libraries I need to be sure that my needs can be covered.

# Acceptance criteria

- Needs expressed by SRG and SRF app development teams have been discussed.
- Corresponding player development tasks have been created.

# Tasks

- [x] Discuss.
- [x] Create Letterbox Apple required tasks.
- [x] Create Pillarbox Apple required tasks.
- [x] Create Letterbox Android required tasks.
- [x] Create Pillarbox Android required tasks.

**Comment by defagos** [comment]
Play SRG needs:

- Be able to apply user consent configuration changes for comScore and Commanders Act separately, i.e. be able to enable or disable these services on-the-fly at any time.

SRF needs:

-

**Comment by defagos** [comment]
API proposal: Use the strategy pattern so that each constructed event gets the most recent consent list just before sending the event.

**Comment by defagos** [comment]
Tasks available for Apple platforms:

- [Letterbox](https://github.com/SRGSSR/srganalytics-apple/issues/66).
- [Pillarbox](https://github.com/SRGSSR/pillarbox-apple/issues/524).
