### ISSUE TITLE
[Letterbox question] Kill the kill switch?

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-documentation#51]
**As a player team** and following the EF 2023 on iOS / tvOS we need to decide whether the kill switch should be kept or not.

# Acceptance criteria

- The question has been decided.

# Tasks

- [x] Discuss and decide.
- [x] Open issue / PR [Apple platforms](https://github.com/SRGSSR/srgletterbox-apple/pull/314).
- [x] Open issue / PR [Android](https://github.com/SRGSSR/srgletterbox-android/issues/518).
- [x] Open issue / PR for the [web](https://github.com/SRGSSR/srgletterbox-web/pull/877).

**Comment by defagos** [comment]
The feature might still be in use for other purposes (e.g. managing DVR to on-demand transition in SwissTXT event streams).

Following the EF 2023 incident we decided to avoid temporary livestream URL changes in the future. So we might take more risks in removing the feature now that Letterbox is in maintenance mode.

We therefore decided not to remove the kill switch for the moment, especially after a single incident.

**Comment by defagos** [comment]
RSI has issues with the Telegiornale because of metadata updates around 9 PM. These should be mitigated but we have a second incident now, so we should discuss the matter again.

On Apple platforms I removed the kill switch on a [dedicated branch](https://github.com/SRGSSR/srgletterbox-apple/tree/kill-switch-removal) and SwissTXT behaviors work well. It is likely we could remove the kill switch if there is a common agreement.

**Comment by defagos** [comment]
We have decided to kill the kill switch. The kill is dead, long live the kill.
