### ISSUE TITLE
Rate login solutions

### ISSUE THREAD

**Issue by amtins** [SRGSSR/pillarbox-documentation#59]
**As a login PO/PM** I need a feedback from development teams regarding the login solutions that have been evaluated.

# Acceptance criteria

- The received document has been filled and returned

# Tasks

- [x] ~Evaluate javascript sample.~
- [x] Fill received document.
- [x] Return document to the GD.

**Comment by defagos** [comment]
Done and sent.
