### ISSUE TITLE
Discuss resource selection

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-documentation#67]
**As an SRG SSR user** I want to have the best possible stream when playing some content. **As Pillarbox developers** we want a common understanding of what resource should be played, given what we receive from the SRG SSR backend.

# Acceptance criteria

- Current resource selection implementation has been discussed (comparison between current implementation).
- Dedicated alignment tasks have been created.

# Hints

- Having the backend filter the resources so that all platforms have consistent behavior is an option.

# Tasks

- [x] Discuss current implementations and their differences.
- [x] Discuss the case of missing resources (e.g. after start date has been reached).
- [x] Decide what to do and create dedicated tasks.

**Comment by defagos** [comment]
Discussed within the team.

# Current status

- Platforms receive all resources, including those not playable on some platform (e.g. DASH on iOS or RTMP).
- Platforms currently are not _too smart_ and basically consider streaming methods they support.
- Resources are not otherwise ordered in any way so for example if a livestream precedes a DVR resource it will be selected first.
