### ISSUE TITLE
Discuss nested and overlapping blocked time range support

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-documentation#68]
**As an editor** I want blocked time ranges not to be reachable, even if nested or overlapping. **As a Pillarbox development team** we would like to possibly have a common answer to this need.

# Acceptance criteria

- Strategies to address overlapping and blocked time ranges have been discussed and documented.
- A common solution has been designed if possible.

# Hints

- Having the backend fix the issue and the clients deal with such cases as undefined behavior can be an option.

# Tasks

- [ ] Update web demo to have examples of such content. Check behavior.
- [ ] Update Android demo to have examples of such content. Check behavior.
- [ ] Discuss and document.

**Comment by defagos** [comment]
Discussed within the team.

# Backend

We will ask the backend team to flatten overlapping and nested segments. This way the behavior is implemented consistently and the backend chooses how such changes are handled (e.g. a single or multiple blocked reasons could be returned for some blocked time range in such cases, but the backend again decides).

**Comment by defagos** [comment]
The discussion has been started with the backend team but [is not finished yet](https://srgssr-ch.atlassian.net/wiki/spaces/SRGPLAY/pages/943685633/Developer+Meeting+2024-05-29).

**Comment by defagos** [comment]
@amtins will slightly revisit the ticket linked on Confluence as its title / content might be slightly misleading.

**Comment by defagos** [comment]
[A new issue](https://srgssr-ch.atlassian.net/browse/PLAY-6665) has been created in the backend backlog.

**Comment by defagos** [comment]
We have decided to keep the topic for future SAM services, thus avoiding work on the legacy IL services. The associated [JIRA issue](https://srgssr-ch.atlassian.net/browse/PLAY-6665) has been closed.
