### ISSUE TITLE
Timebox: live pause / recovery strategy

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-documentation#9]
**As developers** we need to agree on a playback failure recovery strategy.

# Acceptance criteria

- Recovery strategies have been agreed on and dedicated tasks have been created if needed.

# Tasks

- [x] Share existing Letterbox recovery strategies.
- [x] Answer: Should we recover from failures after a live stream was paused for a while (_behind live_ exception on Android)?
- [x] Answer: Should we stop a livestream instead of pausing it as we did in Letterbox?
