### ISSUE TITLE
Setup QoS / QoE AWS test infrastructure

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-documentation#92]
**As a Pillarbox developer** I would like to have a QoS / QoE test infrastructure to which I can send events collected by the platform player I am working on.

# Acceptance criteria

- Event dispatcher and data storage / visualization tools are available.
- Clients send data to our test platform, and this data is visualized in the simplest possible way.
- Monthly costs stay reasonable (< Snitch).
- We have the access level needed to administer our platform.

# Tasks

- [x] Discuss QoS / QoE AWS infrastructure needs and cost structure.
- [x] Estimate potential costs.
- [x] Deploy existing dispatcher / visualization tools.

**Comment by amtins** [comment]
I asked the sysadmins how to deploy the service. It's in progress.

**Comment by amtins** [comment]
Commented the following task https://github.com/SRGSSR/pillarbox-event-dispatcher/issues/1#issuecomment-2338688093

**Comment by defagos** [comment]
We will monitor costs in the upcoming weeks / months.
